# Generated by Django 2.2.4 on 2020-09-11 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_app', '0002_pet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='liked_pets',
            field=models.ManyToManyField(related_name='users_who_liked', to='pet_app.Pet'),
        ),
    ]
